---
openapi: "3.0.1"
info:
  title: "Zana HMIS — pharmacy API"
  version: "v1"
paths:
  /api/v1/pharmacy/prescriptions/uid/{uid}/dispense:
    post:
      tags:
      - "pharmacy-dispense-controller"
      operationId: "dispense_1"
      parameters:
      - name: "uid"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DispenseRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PrescriptionView"
  /api/v1/pharmacy/prescriptions/worklist:
    get:
      tags:
      - "pharmacy-dispense-controller"
      operationId: "worklist_1"
      parameters:
      - name: "patientType"
        in: "query"
        required: true
        schema:
          type: "string"
          enum:
          - "OUTPATIENT"
          - "OUTSIDER"
          - "INPATIENT"
      - name: "patientUid"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PrescriptionView"
  /api/v1/pharmacy/sale-orders:
    get:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "worklist"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/SaleOrderDto"
    post:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "create"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaleOrderRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SaleOrderDto"
  /api/v1/pharmacy/sale-orders/details/uid/{detailUid}:
    delete:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "deleteDetail"
      parameters:
      - name: "detailUid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "204":
          description: "No Content"
  /api/v1/pharmacy/sale-orders/uid/{uid}:
    get:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "getByUid"
      parameters:
      - name: "uid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SaleOrderDto"
  /api/v1/pharmacy/sale-orders/uid/{uid}/archive:
    post:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "archive"
      parameters:
      - name: "uid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SaleOrderDto"
  /api/v1/pharmacy/sale-orders/uid/{uid}/cancel:
    post:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "cancel"
      parameters:
      - name: "uid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SaleOrderDto"
  /api/v1/pharmacy/sale-orders/uid/{uid}/details:
    post:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "addDetail"
      parameters:
      - name: "uid"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaleOrderDetailRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SaleOrderDetailDto"
  /api/v1/pharmacy/sale-orders/uid/{uid}/dispense:
    post:
      tags:
      - "pharmacy-sale-order-controller"
      operationId: "dispense"
      parameters:
      - name: "uid"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "pharmacyUid"
        in: "query"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SaleOrderDto"
  /api/v1/pharmacy/stock/uid/{pharmacyUid}/items:
    get:
      tags:
      - "pharmacy-stock-controller"
      operationId: "stockStatus"
      parameters:
      - name: "pharmacyUid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/StockStatusDto"
  /api/v1/pharmacy/stock/uid/{pharmacyUid}/items/uid/{medicineUid}/batches:
    get:
      tags:
      - "pharmacy-stock-controller"
      operationId: "batches"
      parameters:
      - name: "pharmacyUid"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "medicineUid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/StockBatchDto"
  /api/v1/pharmacy/stock/uid/{pharmacyUid}/items/uid/{medicineUid}/movements:
    get:
      tags:
      - "pharmacy-stock-controller"
      operationId: "movements"
      parameters:
      - name: "pharmacyUid"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "medicineUid"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/StockMovementDto"
  /api/v1/pharmacy/stock/update:
    post:
      tags:
      - "pharmacy-stock-controller"
      operationId: "updateStock"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StockUpdateRequest"
        required: true
      responses:
        "204":
          description: "No Content"
components:
  schemas:
    DispenseRequest:
      required:
      - "issued"
      - "pharmacyUid"
      type: "object"
      properties:
        pharmacyUid:
          type: "string"
        issued:
          type: "number"
    PrescriptionView:
      type: "object"
      properties:
        uid:
          type: "string"
        status:
          type: "string"
        settled:
          type: "boolean"
        medicineUid:
          type: "string"
        patientUid:
          type: "string"
        patientBillUid:
          type: "string"
        paymentType:
          type: "string"
        membershipNo:
          type: "string"
        insurancePlanUid:
          type: "string"
        clinicianUserUid:
          type: "string"
        issuePharmacyUid:
          type: "string"
        consultationUid:
          type: "string"
        nonConsultationUid:
          type: "string"
        admissionUid:
          type: "string"
        patientType:
          type: "string"
          enum:
          - "OUTPATIENT"
          - "OUTSIDER"
          - "INPATIENT"
        qty:
          type: "number"
        issued:
          type: "number"
        balance:
          type: "number"
        orderedAt:
          type: "string"
          format: "date-time"
        approvedAt:
          type: "string"
          format: "date-time"
    SaleOrderDetailDto:
      type: "object"
      properties:
        uid:
          type: "string"
        medicineUid:
          type: "string"
        patientBillUid:
          type: "string"
        issuePharmacyUid:
          type: "string"
        qty:
          type: "number"
        issued:
          type: "number"
        balance:
          type: "number"
        status:
          type: "string"
        payStatus:
          type: "string"
        dosage:
          type: "string"
        frequency:
          type: "string"
        route:
          type: "string"
        days:
          type: "string"
    SaleOrderDetailRequest:
      required:
      - "medicineUid"
      - "qty"
      type: "object"
      properties:
        medicineUid:
          type: "string"
        qty:
          type: "number"
        dosage:
          type: "string"
        frequency:
          type: "string"
        route:
          type: "string"
        days:
          type: "string"
    SaleOrderDto:
      type: "object"
      properties:
        uid:
          type: "string"
        "no":
          type: "string"
        paymentType:
          type: "string"
        status:
          type: "string"
        comments:
          type: "string"
        pharmacyUid:
          type: "string"
        pharmacistUid:
          type: "string"
        customerUid:
          type: "string"
        customerNo:
          type: "string"
        customerName:
          type: "string"
        details:
          type: "array"
          items:
            $ref: "#/components/schemas/SaleOrderDetailDto"
    SaleOrderRequest:
      required:
      - "pharmacistUid"
      - "pharmacyUid"
      type: "object"
      properties:
        pharmacyUid:
          type: "string"
        pharmacistUid:
          type: "string"
        customerUid:
          type: "string"
        customerName:
          type: "string"
        customerGender:
          type: "string"
        customerPhoneNo:
          type: "string"
        customerAddress:
          type: "string"
        comments:
          type: "string"
    StockBatchDto:
      type: "object"
      properties:
        uid:
          type: "string"
        pharmacyUid:
          type: "string"
        medicineUid:
          type: "string"
        batchNo:
          type: "string"
        manufacturedDate:
          type: "string"
          format: "date"
        expiryDate:
          type: "string"
          format: "date"
        receivedQty:
          type: "number"
        remainingQty:
          type: "number"
    StockMovementDto:
      type: "object"
      properties:
        uid:
          type: "string"
        pharmacyUid:
          type: "string"
        medicineUid:
          type: "string"
        movementType:
          type: "string"
        qtyIn:
          type: "number"
        qtyOut:
          type: "number"
        runningBalance:
          type: "number"
        reference:
          type: "string"
        occurredAt:
          type: "string"
          format: "date-time"
    StockStatusDto:
      type: "object"
      properties:
        uid:
          type: "string"
        pharmacyUid:
          type: "string"
        medicineUid:
          type: "string"
        stock:
          type: "number"
    StockUpdateRequest:
      required:
      - "medicineUid"
      - "pharmacyUid"
      - "stock"
      type: "object"
      properties:
        pharmacyUid:
          type: "string"
        medicineUid:
          type: "string"
        stock:
          type: "number"
