package com.otapp.hmis.billing.domain;

import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Spring Data JPA repository for {@link PatientCreditNote}.
 *
 * <p>PCN document numbers are generated by DocumentNumberService (P2 scope)
 * using {@code seq_pcn_no} (V13) — no MAX(id)+1 query needed here.
 */
public interface PatientCreditNoteRepository extends JpaRepository<PatientCreditNote, Long> {

    Optional<PatientCreditNote> findByUid(String uid);

    Optional<PatientCreditNote> findByNo(String no);
}
