package com.otapp.hmis.billing.domain;

import com.otapp.hmis.shared.domain.AuditableEntity;
import com.otapp.hmis.shared.domain.Money;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * The refund instrument (PatientCreditNote.java:35 — legacy table {@code patient_credit_notes}).
 *
 * <p>A PCN is created on cancellation of a paid charge. It carries a positive {@code amount}
 * equal to the full bill amount. Status is always PENDING (never auto-applied in legacy).
 *
 * <p>The document number format is: {@code PCN{EAT-yyyyMMdd}-{nextval(seq_pcn_no)}}
 * (built by DocumentNumberService — P2 scope). This entity holds the generated number
 * once assigned.
 *
 * <p>Legacy citations:
 * <ul>
 *   <li>Entity shape: domain/PatientCreditNote.java:35</li>
 *   <li>Creation: PatientResource.java:643-654</li>
 *   <li>PCN number: accessories/Formater.java:14-17</li>
 * </ul>
 */
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
@Table(name = "patient_credit_notes")
public class PatientCreditNote extends AuditableEntity {

    /**
     * PCN document number (UNIQUE). Format: PCN{EAT-yyyyMMdd}-{nextval(seq_pcn_no)}.
     * Generated by DocumentNumberService (P2). Must satisfy the unique constraint.
     */
    @NotBlank
    @Column(name = "no", length = 60, nullable = false, unique = true)
    private String no;

    /** Loose cross-module ref to the patient (nullable — legacy PatientCreditNote.java:38). */
    @Column(name = "patient_uid", length = 26)
    private String patientUid;

    /**
     * Full bill amount (positive). Signed-amount refund is NOT legacy (CR-03 rejected).
     * PatientResource.java:644.
     */
    @NotNull
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "amount",   column = @Column(name = "amount",   precision = 19, scale = 2, nullable = false)),
        @AttributeOverride(name = "currency", column = @Column(name = "amount_currency", length = 3, nullable = false))
    })
    private Money amount;

    /** Cause label (e.g. "Canceled consultation", "Canceled lab test"). PatientResource.java:645. */
    @Column(name = "reference", length = 255)
    private String reference;

    /** Always PENDING (PatientCreditNoteServiceImpl.java:33-40). */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    private CreditNoteStatus status = CreditNoteStatus.PENDING;

    /**
     * Net-new traceability: loose ref to the cancelled bill uid (no FK).
     * Not present in legacy but added per build-spec §1.2 for audit trail.
     */
    @Column(name = "patient_bill_uid", length = 26)
    private String patientBillUid;

    /** Loose cross-module ref to the business day. */
    @NotBlank
    @Column(name = "business_day_uid", length = 26, nullable = false)
    private String businessDayUid;

    // -------------------------------------------------------------------------
    // Business constructor
    // -------------------------------------------------------------------------

    /**
     * Create a credit note for a cancelled bill.
     *
     * @param no             PCN document number (from DocumentNumberService — P2)
     * @param patientUid     loose ref to the patient
     * @param amount         full bill amount
     * @param reference      cause label
     * @param patientBillUid net-new traceability ref to the cancelled bill
     * @param businessDayUid current open business day uid
     */
    public PatientCreditNote(String no, String patientUid, Money amount,
                             String reference, String patientBillUid,
                             String businessDayUid) {
        this.no = no;
        this.patientUid = patientUid;
        this.amount = amount;
        this.reference = reference;
        this.status = CreditNoteStatus.PENDING;
        this.patientBillUid = patientBillUid;
        this.businessDayUid = businessDayUid;
    }
}
