package com.otapp.hmis.billing.domain;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

/**
 * Spring Data JPA repository for {@link PatientCreditNote}.
 *
 * <p>PCN document numbers are generated by {@code DocumentNumberService} (P2) using
 * {@code seq_pcn_no} (V13) — {@link #nextPcnNo()} performs the single atomic {@code nextval}
 * that replaces the legacy {@code MAX(id)+1} race (CR-09). No collision-prone MAX query exists here.
 */
public interface PatientCreditNoteRepository extends JpaRepository<PatientCreditNote, Long> {

    Optional<PatientCreditNote> findByUid(String uid);

    Optional<PatientCreditNote> findByNo(String no);

    /** Credit notes for a patient, newest first (cashier refund-instrument listing). */
    List<PatientCreditNote> findByPatientUidOrderByCreatedAtDesc(String patientUid);

    /**
     * Advance {@code seq_pcn_no} and return the raw BIGINT. The service formats this as
     * {@code PCN{yyyyMMdd}-{seq}} via {@code DocumentNumberService}. One atomic {@code nextval}
     * per call — collision-free, unlike the legacy {@code SELECT MAX(id)+1} request idiom
     * (04-extract-creditnote-numbering-refund.md §4, CR-09).
     */
    @Query(nativeQuery = true, value = "SELECT nextval('seq_pcn_no')")
    Long nextPcnNo();
}
