package com.otapp.hmis.billing.domain;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Spring Data JPA repository for {@link PatientCreditNote}.
 *
 * <p>PCN document numbers are generated by the shared {@code DocumentNumberService}
 * ({@code com.otapp.hmis.shared.documentnumber}, promoted in inc-08 Q11) using {@code seq_pcn_no}
 * (V13) — one atomic {@code nextval} that replaces the legacy {@code MAX(id)+1} race (CR-09). The
 * {@code nextval} is issued generically by the shared service via {@code EntityManager}, so no
 * collision-prone MAX query and no per-type {@code nextval} method live in this domain repository.
 */
public interface PatientCreditNoteRepository extends JpaRepository<PatientCreditNote, Long> {

    Optional<PatientCreditNote> findByUid(String uid);

    Optional<PatientCreditNote> findByNo(String no);

    /** Credit notes for a patient, newest first (cashier refund-instrument listing). */
    List<PatientCreditNote> findByPatientUidOrderByCreatedAtDesc(String patientUid);
}
